# 基本信息
title: 个人博客
author: mrzhqiang
email: qiang.zhang0314@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  路漫漫其修远兮，吾将上下而求索。

# 显示摘要
show_excerpts: false # set to true to show excerpts on the homepage

# 永久链接
permalink: pretty

# 服务
host: "localhost"

# 插件
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# 单个页面的最大帖子数量
paginnate: 10

# 自动索引
kramdown:
  auto_ids: true

# 工具：主要 GitHub Pages 流量有限（据说每个月 100Gb），使用 CDN 可以节省流量
cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"

# 仓库工具
bootstrap_path: "bootstrap-4.3.1-dist"
fontawesome_path: "fontawesome-free-5.8.2-web"

# 全局变量
repo:     "https://github.com/mrzhqiang/mrzhqiang.github.io"
jekyll:   "https://jekyllrb.com/"
