# 基本信息
title: mrzhqiang·个人博客
author: mrzhqiang
email: qiang.zhang0314@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  路漫漫其修远兮，吾将上下而求索。
# social_image_path:
# social_logo_path:

show_excerpts: false # set to true to show excerpts on the homepage

# 依赖
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

# 永久链接
permalink: pretty

# 服务
host: "localhost"
post: 8080
baseurl: ""
encoding: UTF-8

# 插件
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

repo:     "https://github.com/mrzhqiang/mrzhqiang.github.io"
jekyll:   "https://jekyllrb.com/"

# 依赖
cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  css_hash:         "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  js_hash:          "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
  js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
  js_bundle_hash:   "sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  popper_hash:      "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"

# 本地依赖
bootstrap_path: "bootstrap-4.3.1-dist"
